### PR TITLE
[PRM-1632]:  added content when user has fulfilled all obligations

### PR DESCRIPTION
**Pull request by BackRowOla**

### CODE REVIEW

**Comment by BackRowOla** [comment]
Some todo's to be changed with PRM-1640:
- [todo 1](https://github.com/hmrc/penalties-frontend/pull/234/files#diff-41034673dd40877d5d2ed4a88d6fa22024586f56cad0ace4494b455549e22aafR73)
- [todo 2 ](https://github.com/hmrc/penalties-frontend/pull/234/files#diff-ca5386d3a41721dba5e4e48b4484f5df130ca849f8648f232bf546cf7b425bfaR689)
- [todo 3 ](https://github.com/hmrc/penalties-frontend/pull/234/files#diff-ca5386d3a41721dba5e4e48b4484f5df130ca849f8648f232bf546cf7b425bfaR701)

**Review by AndrewRButcher — APPROVED** [review]
Waiting on AT updates before merging

**Review by AndrewRButcher — CHANGES_REQUESTED** [review]
Needs rebasing

**Review by AndrewRButcher — DISMISSED** [review]
Ready to merge with ATs

**Review by AndrewRButcher — APPROVED** [review]

**Pull request merged**
