### PR TITLE
PRM-1082 Corrected service name in page title

### PR DESCRIPTION
**Pull request by AndrewRButcher**

### CODE REVIEW

**Comment by AndrewRButcher** [comment]
No AT update required
Appeals FE is correct no change needed

**Comment by LewisMitchell** [comment]
Could you rebase this please?

**Review by LewisMitchell — CHANGES_REQUESTED** [review]
Since we have a test in the calc and compliance pages for the title, do we want to add a test in the index page as well?

**Comment by AndrewRButcher** [comment]
Rebased + added extra test

**Comment by LewisMitchell** [comment]
Sorry, could you rebase again? :sorry:

**Comment by AndrewRButcher** [comment]
Done ✅

**Review by LewisMitchell — APPROVED** [review]

**Pull request merged**
